#!/bin/sh

# shellcheck source=startup/common
. /startup/common
if [ "${CREATE_RELATIONSHIPS:-False}" = "True" ]
then
  red django-admin create_relationships
else
  echo "Set CREATE_RELATIONSHIPS=True to run django-admin create_relationships"
fi
