#!/bin/sh

# shellcheck source=startup/common
. /startup/common
if [ "${CREATE_INITIAL_REVISIONS:-False}" = "True" ];
then
  red django-admin createinitialrevisions
else
  echo "Set CREATE_INITIAL_REVISIONS=True to enable django-admin createinitialrevisions"
fi
