#!/bin/sh

# shellcheck source=startup/common
. /startup/common
if [ "${COMPILE_MESSAGES:-False}" = "True" ]
then
  red django-admin compilemessages
else
  echo "Set COMPILE_MESSAGES=True to run django-admin compilemessages"
fi
