#!/bin/bash

if [ "$USE_GUNICORN" == "True" ]; then
	gunicorn wsgi -b 0.0.0.0:5000 --timeout 120 --workers=3 --threads=3 --worker-connections=1000 --pythonpath="/startup" --access-logfile - --error-logfile -
else
	uvicorn asgi:application --host 0.0.0.0 --port 5000 --app-dir "/startup"
fi
